

```{r}
library(monocle3)
library(SeuratWrappers)
library(Seurat)
library(ggplot2)
```



```{r}
Idents(F2.stem) <- "Germ.cluster.ids"
Idents(F3.stem) <-"Germ.cluster.ids"
```

```{r}
DimPlot(F2.stem, reduction = "wnn.umap2Germ")
DimPlot(F3.stem, reduction = "wnn.umap2Germ", split.by = "Treatment")
```

```{r}
F2.ssc5 <- subset(F2.stem, idents="SSC5")
F3.ssc5 <- subset(F3.stem, idents="SSC5")
```


```{r}
DimPlot(F2.ssc5, reduction = "wnn.umap2Germ", split.by = "Treatment")
DimPlot(F3.ssc5, reduction = "wnn.umap2Germ", split.by = "Treatment")
```

```{r}
VlnPlot(F2.stem, c("Plvap","Bcl6b","Id4","Nanos3","Gfra1","Lin28a"))
```

```{r}
VlnPlot(F3.stem, c("Plvap","Bcl6b","Id4","Nanos3","Gfra1","Lin28a"))
```



```{r}
F2 <- read.csv("F2 SSC5 markers.csv")  
FoldChangePsDEs <- F2[,2]
names(FoldChangePsDEs) <- as.character(F2[,1])
FoldChangePsDEs <- sort(FoldChangePsDEs, decreasing = TRUE)



idPsDEsA <- names(FoldChangePsDEs)
F2$ENTREZID <- convertIDs(idPsDEsA, "SYMBOL","ENTREZID", org.Mm.eg.db)




F3 <- read.csv("F3 SSC5 markers.csv")  
FoldChangePsDEs <- F3[,2]
names(FoldChangePsDEs) <- as.character(F3[,1])
FoldChangePsDEs <- sort(FoldChangePsDEs, decreasing = TRUE)



idPsDEsS <- names(FoldChangePsDEs)
F3$ENTREZID <- convertIDs(idPsDEsS, "SYMBOL","ENTREZID", org.Mm.eg.db)



DATA <- list(F2=F2$ENTREZID, F3=F3$ENTREZID)

```


```{r}
str(DATA)
ssc5 <- compareCluster(geneCluster = DATA, fun = enrichGO, ont = "BP",
                    pAdjustMethod = "BH",
                    pvalueCutoff  = 0.05,
                    qvalueCutoff  = 0.05,
                    universe= AllDEs$ENTREZID,
                    OrgDb = 'org.Mm.eg.db',
                    readable=TRUE)

head(ssc5) 
write.csv(ssc5, "F2 F3 ssc5.csv")
ssc5.filter <-simplify(ssc5, cutoff = 0.7, by = "p.adjust", select_fun = min)

write.csv(ssc5.filter, "ssc5.filter.csv")
```

```{r}
a <- c("positive regulation of signal transduction by p53 class mediator","ribosome biogenesis","signal transduction by p53 class mediator","cytoplasmic translation","cell cycle phase transition","rRNA processing","signal transduction in response to DNA damage")

p1 <- dotplot(ssc5, showCategory = a, font.size=12, x="Count")+ facet_grid(~Cluster)+theme(axis.title = element_text(size=8))+theme(axis.text = element_text(color="black", size=8))+theme(legend.title = element_text(size=8)+theme(legend.text = element_text(size = 8)))+theme(legend.key.width = unit(0.2,"cm"))+theme(legend.key.height = unit(0.3,"cm"))+theme(legend.text = element_text(size = 6))+theme(legend.title = element_text(size = 6))+xlab("Gene Counts")+theme(plot.title = element_text(size=10,face = "bold"))+theme(axis.title = element_text(size = 8))+theme(axis.text.x = element_text(angle = 30, size=6))
p1

ggsave("F2 F3 ssc5.GO.BP.tiff", dpi = 300, width = 8, height = 6)
```
```{r}
c <- c("signal transduction by p53 class mediator","signal transduction in response to DNA damage","ribosome biogenesis")
#"rRNA processing"
cnetplot(
  ssc5,
  showCategory = c,
  foldChange = NULL,
  colorEdge = T,
  circular = T,
  node_label = "all",
  cex_category = 0.01,
  cex_gene = 0.02,
  cex_label_category = 2.5,
  cex_label_gene = 2,
color.params = list(edge=c("#E5C494","#CBCE91FF","#76528BFF")),
  
  
 
)+scale_fill_manual(values=c("#CBCE91FF","#76528BFF"))


ggsave("Go.cnetplot.tiff", dpi = 300, width = 15, height = 15, bg = "white")
```

```{r}
c <- c("signal transduction by p53 class mediator","signal transduction in response to DNA damage")
#"rRNA processing"
cnetplot(
  SSC5,
  showCategory = c,
  foldChange = NULL,
  colorEdge = F,
  circular = F,
  node_label = "gene",
  cex_category = 0.3,
  cex_gene = 0.2,
  cex_label_category = 1.5,
  cex_label_gene = 1.5,
  legend_n=2,
  x_loc = 3,
  y_loc = 2
 
)+scale_fill_manual(values=c("#00A4CCFF","#D85A7FFF"))+theme(legend.key.width = unit(0.5,"cm"))+theme(legend.key.height = unit(0.5,"cm"))+theme(legend.text = element_text(size = 10))


ggsave("Go.cnetplot1.tiff", dpi = 300, width = 6, height = 6, bg = "white")
```



```{r}
# Compare F2 vs F3 SSC5 marker genes
df <- read.csv("F2 F3 SSC5 markers.csv")  
Generation<-df[,3]
names(Generation) <- as.character(df[,1])


id <- names(Generation)
df$ENTREZID <- convertIDs(id, "SYMBOL","ENTREZID", org.Mm.eg.db)


mydf <- data.frame(Entrez=df$ENTREZID, Generation=Generation)

mydf$group[mydf$Generation < 2] <- "F2" 
mydf$group[mydf$Generation > 2] <- "F3"
```

```{r}
SSC5 <- compareCluster(Entrez~group, data=mydf,fun = enrichGO, ont = "BP",
                    pAdjustMethod = "BH",
                    pvalueCutoff  = 0.05,
                    qvalueCutoff  = 0.05,
                    universe= AllDEs$ENTREZID,
                    OrgDb = 'org.Mm.eg.db',
                    readable=TRUE)

```

```{r}
a <- c("positive regulation of signal transduction by p53 class mediator","ribosome biogenesis","signal transduction by p53 class mediator","cytoplasmic translation","cell cycle phase transition","rRNA processing","signal transduction in response to DNA damage")

p2 <- dotplot(SSC5, showCategory = a, font.size=12, x="group")+theme(axis.title = element_text(size=12))+theme(axis.text.x = element_text(color="black", size=12,angle = 0, vjust = 0.5, hjust= ))+theme(legend.title = element_text(size=8)+theme(legend.text = element_text(size = 8)))+theme(legend.key.width = unit(0.2,"cm"))+theme(legend.key.height = unit(0.3,"cm"))+theme(legend.text = element_text(size = 8))+theme(legend.title = element_text(size = 8))+xlab("")+theme(plot.title = element_text(size=10,face = "bold"))+theme(axis.title = element_text(size = 12))+scale_x_discrete(labels=c('F2', 'F3'))
p2

ggsave("Go.SSC5.tiff", dpi = 300, width = 4, height = 4)
```

